version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "kvadodb"
      MYSQL_ROOT_PASSWORD: root
       
    ports:
      - "8000:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: testkvado
